services:
  - type: web
    name: it-helpdesk-oneplace
    runtime: python
    buildCommand: "npm install && npm run build && pip install -r backend/requirements.txt && python backend/manage.py migrate && python backend/manage.py collectstatic --noinput"
    startCommand: "gunicorn --chdir backend core.wsgi:application --log-file -"
    envVars:
      - key: DATABASE_URL
        sync: false # Set this to your Neon database URL in the Render dashboard
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
