# Generated by Django 5.2.5 on 2026-01-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_category_organization_ticket_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sla_status',
            field=models.CharField(choices=[('ON_TRACK', 'On Track'), ('AT_RISK', 'At Risk'), ('BREACHED', 'Breached')], default='ON_TRACK', max_length=20),
        ),
    ]
