# Generated by Django 5.2.5 on 2026-01-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_kbtopic_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='feedback_rating',
            field=models.IntegerField(blank=True, help_text='Rating from 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='feedback_text',
            field=models.TextField(blank=True, help_text='User feedback comments', null=True),
        ),
    ]
